### ISSUE TITLE
Input isn't passed to the external program

### ISSUE THREAD

**Issue by ekd123** [sellout/external-program#14]
(external-program:run "cat" nil :input *standard-input*)
You see, no matter how I hit enter, `cat` won't print anything. 
Is it a bug? How to work it around?

**Comment by pipping** [comment]
```
sbcl \
  --eval '(require :external-program)' \
  --eval '(external-program:run "cat" nil :input (make-string-input-stream (format nil "foo~%")) :output *standard-output*)' \
  --quit
```
Prints foo and a newline for me, like it should.
```
echo foo | sbcl \
  --eval '(require :external-program)' \
  --eval '(external-program:run "cat" nil :input *standard-input* :output *standard-output*)' \
  --quit
```
Also prints foo and a newline for me, like it should.

I think there is no bug here.
